### ISSUE TITLE
Nouveaux champs sur Teaching

### ISSUE THREAD

**Issue by ah1508** [Nourallazkani/org.jrsfrance.cpa.api#16]
Ajouter 3 nouveaux champs :
"contact" 
"contactPhone" 
"contactMailAddress" 

Ils sont tous les 3 de type "String" et servent à préciser le contact pour un enseignement. Car une université peut avoir plusieurs enseignements, avec à chaque fois un contact différent.

**Comment by Nourallazkani** [comment]
c'est bon aussi
