### ISSUE TITLE
Workshop

### ISSUE THREAD

**Issue by ah1508** [Nourallazkani/org.jrsfrance.cpa.api#19]
Créer une entité + table + endpoint pour les ateliers de conversation. Un atelier de conversation est défini par : 
- une organisation (celle qui organise le workshop)
- une adresse
- une date et heure de début
- une date et heure de fin
- un sujet
- une description

**Comment by Nourallazkani** [comment]
les atelier de conversation aurait avantage a être coïncides comme d’événement.
