### ISSUE TITLE
RefugeeEndpoint

### ISSUE THREAD

**Issue by ah1508** [Nourallazkani/org.jrsfrance.cpa.api#22]
méthode creatMeetingRequest à revoir :
- Problème sur le path du @RequestMapping. Pourquoi meetingRequests/meetingRequest ?
- plutôt que de faire la vérification sur le accessKey (ce qu'on fait pour le GET et le DELETE), on pourrait s'en servir pour récupérer le refugié correspondant et s'en servir pour valoriser la propriété refugee de la MeetingRequest sur le point d'être créée (reprendre donc la ligne 170 et 171).

méthode getMeetingRequests à revoir :
- erreur dans la requête hql. Si la classe Refugee avait une propriété List<MeetingRequest> meetingRequests on pourrait l'utiliser plutôt que de faire une requête hql.

**Comment by Nourallazkani** [comment]
merci Alaric, j'ai corriger la faute de meetingRequests/meetingRequest,

**Comment by ah1508** [comment]
OK. N'oublie pas de commiter. Au passage, renommer creatMeetingRequest 
en creat_e_MeetingRequest
Et pour le troisième point, il concerne la méthode getMeetingRequests 
(j'ai corrigé dans le texte de l'isssue).
