### ISSUE TITLE
Ajout d'une entité 'Administrator'

### ISSUE THREAD

**Issue by ah1508** [Nourallazkani/org.jrsfrance.cpa.api#4]
Ajouter une entité 'Administrator' (mappée vers une table du même nom). Les administrateurs sont ceux qui peuvent administrer l'application depuis le back office. Champs (en plus de l'id) : 

firstName;
lastName;
mailAddress
phoneNumber;
account (de type Account)

**Comment by Nourallazkani** [comment]
d'accord..
